#!/usr/bin/env bash
set -euo pipefail
input_file="$1"
output_dir="$2"
filename="$(basename "$input_file")"

# Strip YAML frontmatter (between --- delimiters)
body="$(awk '/^---/{if(NR==1){in_fm=1; next} else if(in_fm){in_fm=0; next}} !in_fm{print}' "$input_file")"

# Wrap in Codex prompt template
cat > "$output_dir/$filename" <<EOF
<!-- Codex Skill: $filename -->
<!-- Auto-generated by lamella adapter pipeline. Do not edit directly. -->

$body
EOF
